[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "Posts"
  url = "post/"
  weight = -100

# Submenus are done this way: parent -> identifier
# [[main]]
#   name = "Links"
#   identifier = "Links"
#   weight = -108
# [[main]]
#   parent = "Links"
#   name = "LinkedIn"
#   url = "https://www.linkedin.com/"
# [[main]]
#   parent = "Links"
#   name = "Twitter"
#   url = "https://twitter.com/"

[[main]]
  name = "About"
  url = "about/"
  weight = -90

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/mikemurray86"
# [[social]]
#   name = "twitter"
#   weight = 2
#   url = "https://twitter.com/#"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/michael-murray-3ba8aa24/"
# [[social]]
#   name = "rss"
#   weight = 4
#   url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "discord"
# url = "https://discord.gg/#"
