name: Build Pages

on:
  push:
    branches:
      - main

env:
  HUGO_VERSION: 0.120.3
  HUGO_ENVIRONMENT: production
  HUGO_ENV: production

jobs:
  build:
    name: Build Site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install task
        uses: arduino/setup-task@v1.0.3

      - name: Setup Go environment
        uses: actions/setup-go@v4.1.0
        with:
          go-version-file: './go.mod'
            
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Install Dart Sass
        run: sudo snap install dart-sass

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: build the site
        env:
          BASE_URL: "${{ steps.pages.outputs.base_url }}/"
        run: task build

      - name: upload
        uses: actions/upload-pages-artifact@v1.0.7
        with:
          path: public/

  publish:
    name: Publish the site
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy
        id: deploy
        uses: actions/deploy-pages@v1



